Repository TECLIB/ravada, pull requests merged in 2018-09, with the labels that each got.

#16 Change homepage url
  .github/settings.yml
Labels: documentation

#17 Change url of the project-site
  _config.yml
Labels: build, documentation

#23 Update service worker
  js/share-bar.js
  sw.js
Labels: build, documentation

#27 Modify professional services
  README.md
Labels: documentation

#31 Update cache links
  sw.js
Labels: build, documentation

#32 Delete unnecessary file
  _data/config.yml
Labels: documentation, refactor

#33 Add google group in Readme
  README.md
Labels: documentation

#37 Fix images paths on the project site
  _includes/image-WebP.html
Labels: bug, documentation

#38 Fix the image path on the project site footer
  _includes/footer.html
Labels: bug, documentation
